### ISSUE TITLE
crash during startup

### ISSUE THREAD

**Issue by Lordbaane** [Snownee/Kiwi#11]
* Forge Version: 31.1.14
 * Mod Version: 2.6.5

https://paste.ubuntu.com/p/S6PVqJsq5Q/

**Comment by Snownee** [comment]
Could you provide logs?
Can you reproduce this crash with Kiwi, FruitTrees and Mixin only?

**Comment by Lordbaane** [comment]
[2020-02-21-2.log.gz](https://github.com/Snownee/Kiwi/files/4239677/2020-02-21-2.log.gz)
[debug-2.log.gz](https://github.com/Snownee/Kiwi/files/4239680/debug-2.log.gz)
I hope these help. I hasn't done it since.

**Comment by Snownee** [comment]
I cannot find where the crash is in your logs

**Comment by Lordbaane** [comment]
It is the second time that it has done this, usually after I do an update for another mod, but it has only effected your mods once. Not sure what it could be, but I'd thought I would post it all the same just in case. 
If you can't see anything, them maybe it is just a one-off. I'll close it for now and let you know if it does it again.
