### ISSUE TITLE
Kiwi, Patchouli一起安装时，打开生活调味料的手册游戏崩溃

### ISSUE THREAD

**Issue by RisingInIris2017** [Snownee/Kiwi#13]
#### Kiwi Mod 版本：
Kiwi-1.15.2-2.6.5

#### Forge 版本：

1.15.2-31.1.41

#### 单人游戏 / 多人游戏
单人游戏

#### 安装的 MOD:
Kiwi, Patchouli, [Spice of Life: Carrot Edition](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition)（生活调味料：胡萝卜版），如崩溃报告中所见。

## 崩溃报告的链接
https://paste.ubuntu.com/p/s6P6XJysGz/

### 如何复现
1. 安装上述三个模组，启动游戏。
2. 调整游戏语言为中文（中国）。
3. 打开生活调味料的食物手册。
4. 游戏崩溃。

我已经将问题汇报给生活调味料作者：https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/87
在此感谢你的帮助！

**Comment by BloCamLimb** [comment]
生活调味料坠机和雪尼有什么关系（半恼
