### ISSUE TITLE
Player stuck when entering world in 1.15.2

### ISSUE THREAD

**Issue by ButterSponge39** [Snownee/Kiwi#17]
After updating to 2.8.0 from 2.7.2 I started to get stuck in when I entered the world(I was in a LAN with a friend, it happened to him too). After checking every mod I updated and using Kiwi alone (both 2.8.0 and 2.8.1), I noticed this seems to happen the second time you enter a world/after entering a second world. If you teleport in the air you remain in the position you teleported, the item in your hand(and your hand) appear lower than where they should be, you mine at a slower speed and items and blocks you pick up are bugged. You can still move your camera though. The only way I found to get out of this state is to get killed(you still take damage and commands can kill you). The versions of Forge I used(I tested on both) are 31.2.31 and 31.2.0. Sorry for the long post but I tried to give you as much details
![Item bugged iniventory](https://user-images.githubusercontent.com/69044422/89041389-f4217f80-d34d-11ea-957c-89079906efd9.png)
![Slower mining speed](https://user-images.githubusercontent.com/69044422/89041391-f552ac80-d34d-11ea-8769-80b3594411a2.png)

**Comment by Snownee** [comment]
Please provide your debug.log. It is in logs folder

**Comment by ButterSponge39** [comment]
Here you go!
[debug.log](https://github.com/Snownee/Kiwi/files/5007736/debug.log)
[latest.log](https://github.com/Snownee/Kiwi/files/5007737/latest.log)

**Comment by Snownee** [comment]
Thank you! the fix won't be too late
