### ISSUE TITLE
[1.16.1]  Will not start with Forge 106

### ISSUE THREAD

**Issue by ProsperCraft** [Snownee/Kiwi#19]
* Forge Version:  32.0.106
 * Mod Version: Kiwi-1.16.1-3.2.1.jar
--

https://gist.github.com/ProsperCraft/397f157c329e890dbe33ab7abc360de6

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/chineseworkshop
Known issue. See the first line please. It will be fixed when Forge 1.16.2 is out

**Comment by ProsperCraft** [comment]
Roger that, we will wait on 1.16.2 to include you in TownCraft TWO
