### ISSUE TITLE
Error while loading Kiwi Mod

### ISSUE THREAD

**Issue by alterlove** [Snownee/Kiwi#20]
I get the error: A Kiwi error occurred during the 'create registries' phase
Method public void.

I was using this mod with Tree fruits, and the first time it worked, but now it doesnt, I even removed just the tree mod but the error still there, so its an issue with this library.

![Anotación 2020-08-11 014031](https://user-images.githubusercontent.com/38593578/89841606-aee22680-db73-11ea-9518-1d16e20dec3c.png)

**Comment by Snownee** [comment]
Wrong format

**Comment by alterlove** [comment]
I dont care, if you cant just fix it i'll just drop it and give a bad review, cya.
