### ISSUE TITLE
Crash when starting with ForgeGradle (mc 1.15.2, kiwi 2.8.5, forge 31.2.46)

### ISSUE THREAD

**Issue by Benoxiid** [Snownee/Kiwi#22]
Hi, i'm currently trying to make use of your mod as (new) mod dev...
So, i did a clean install of forge with the IntelliJ ForgeGradle plugin.

- Added "Kiwi-1.15.2-2.8.5.jar" to "/src/libs/",
and added "compile files("src/libs/Kiwi-1.15.2-2.8.5.jar")" (in the dependencies field of build.gradle)

- The game compiles just fine but won't start.

- "Kiwi (kiwi) encountered an error during the create_registries event phase
net.minecraft.util.ResourceLocation.func_110624_b()Ljava/lang/String;"

- The mod is currently empty, no added classes, just a clean install and your jar :)

[debug.log](https://github.com/Snownee/Kiwi/files/5556003/debug.log)
[latest.log](https://github.com/Snownee/Kiwi/files/5556006/latest.log)

**Comment by Snownee** [comment]
hello, you need to use the deobf. version, or use CurseMaven
