### ISSUE TITLE
Server Crashing on Boot

### ISSUE THREAD

**Issue by MFWalter** [Snownee/Kiwi#26]
* Forge Version: 36.1.3
 * Mod Version: 3.4.2
 
I'm pretty sure the report says Kiwi is the source of the crash. Our server went down for it's daily restart and now can't come back up.

https://paste.ubuntu.com/p/vs5jNxCVwS/

**Comment by MFWalter** [comment]
CreeperHost recommanded deleting chineseworkshop-common.toml and uploading it from the client and that seems to have fixed it.

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by NickWilde263** [comment]
@Snownee he make mistake in config file (and he wont look at this issue anymore)
```
...
com.electronwill.nightconfig.core.io.ParsingException: Invalid TOML data: entry "[showRetextureJei]" defined twice in its table.
...
```

**Comment by Snownee** [comment]
Forge's night config api is very buggy. I have made a new api in 1.19...
