### ISSUE TITLE
Crash while loading minecraft

### ISSUE THREAD

**Issue by ym1025** [Snownee/Kiwi#3]
* Minecraft Version:1.14.4
 * Mod Version:1.14.4-2.3.3
Forge version:28.1.58
As above.
mod list: https://hastebin.com/vimalofija.css

**Comment by Snownee** [comment]
No crash report?

**Comment by ym1025** [comment]
https://hastebin.com/mukicopinu.rb

**Comment by Snownee** [comment]
Have you tried to run with Kiwi and ChineseWorkshop only? Did the problem occur too?

**Comment by ym1025** [comment]
It works only kiwi.But when ChineseWorkshop installed,It won't work.
I tell it to ChineseWorkshop's author.

**Comment by ym1025** [comment]
This is issue page of Chinese workshop.
https://github.com/574448121/ChineseWorkshop/issues/17
