### ISSUE TITLE
NetworkInstance 在注册packet的时候有可能造成服务器和客户端id不一致

### ISSUE THREAD

**Issue by warmthdawn** [Snownee/Kiwi#30]
If bug:

 * Forge Version:  1.12.2_2854
 * Mod Version:  1.12.2-0.5.3.32
 * Can you reproduce this issue with relevant mods only?: yes
 
某些情况下，客户端和服务器模组加载顺序不一致，在使用NetworkInstance注册Packet的时候会造成服务端和客户端packet的Id不一样，造成Packet无法解析
如何复现：启动包含kiwi, cuisine, researchtable的服务端和客户端，其中，对服务端文件改名 00-researchtable.jar
连接服务器，researchtable无法使用
（为啥你客户端和服务器mod文件名字不一样？这只是复现bug的一种方式，在隔壁群开神之试炼整合包时，服务端和客户端mod列表完全一致但是同样出现此问题，经判断属同一个bug（使用researchtable命令解锁的时候，客户端发出烹饪熟练度增加的信息)

**Comment by Snownee** [comment]
抱歉，1.12不维护了。主要原因我搭不起来环境了
推荐解决方法：别同时安装
