### ISSUE TITLE
Crashing on Server Startup

### ISSUE THREAD

**Issue by SharkieTV** [Snownee/Kiwi#32]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

Kiwi-1.18.1-fabric-5.2.1.jar

### Modloader version

0.12.12

### Modpack info

Better Minecraft [FABRIC]  1.18.1

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/jV0VLrCP

### Issue description

Server doesn't start up with Kiwi [FABRIC], tested standalone and still same error

**Comment by Snownee** [comment]
fixed. sorry for the inconvenience
