### ISSUE TITLE
Rendering Crash - with Modern Industrialization & Patchouli ?

### ISSUE THREAD

**Issue by SpigotDE** [Snownee/Kiwi#33]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

kiwi-1.18.1-fabric-5.2.2

### Modloader version

0.12.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/the-progressor

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/SpigotDE/f8abf1ee0aaa177dfb8f30b48af4e430

### Issue description

[The Modern Industrialization Owner says it seems its kiwi mod](https://github.com/AztechMC/Modern-Industrialization/issues/229)

Open MI book -> get to the Steam Age Page -> click on Forge ... -> at the page with the diamond drill it crashed

the game crashes client side with rendering crash

[crash-2022-01-13_21.49.26-client.txt](https://github.com/Snownee/Kiwi/files/7872963/crash-2022-01-13_21.49.26-client.txt)

**Comment by SpigotDE** [comment]
It still crashes, maybe you know which mod causes this

**Comment by Snownee** [comment]
please provide latest.log
