### ISSUE TITLE
[Crash with No Telemetry Mod] Server World Gen Crash [Fabric 1.18.1]

### ISSUE THREAD

**Issue by SpigotDE** [Snownee/Kiwi#34]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

Kiwi-1.18.1-fabric-5.2.4.jar

### Modloader version

0.12.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/the-progressor

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/SpigotDE/f3ff05cef85b5da887c706c1403c73e4

### Issue description

Incompatible with No Telemetry mod?

**Comment by Snownee** [comment]
[Kiwi-1.18.1-fabric-5.2.5.zip](https://github.com/Snownee/Kiwi/files/7907581/Kiwi-1.18.1-fabric-5.2.5.zip)

I am having some trouble visiting CurseForge. Just drop the patched version here
