### ISSUE TITLE
Encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by Blackout-tech** [Snownee/Kiwi#35]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

5.2.2 to 5.2.5

### Modloader version

Forge: 39.0.66

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/HRcnuCN3

### Issue description

[Active Mods.txt](https://github.com/Snownee/Kiwi/files/8000548/Active.Mods.txt)

There are the mods I have loaded. ( I need kiwi for snow real magic, and fruit trees )

**Comment by Snownee** [comment]
You can downgrade Forge to 39.0.65 as a workaround

**Comment by Blackout-tech** [comment]
👌
