### ISSUE TITLE
Failed to load correctly

### ISSUE THREAD

**Issue by MC-Valdreth** [Snownee/Kiwi#38]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

6.1.0

### Modloader version

Forge: 40.1.31

### Modpack info

https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-new/files/3815907

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/WWR6jYht

### Issue description

I added Kiwi & Companion to the Medieval Minecraft Modpack and it worked fine with the previous pack version, but since updating to v12 of the pack it now crashes before getting to the main menu stating "Kiwi has failed to load correctly java.lang.reflect.InvocationTargetException: null" Not sure if my crash report has any additional information that the latest.log doesn't, but I've uploaded that aswell: https://pastebin.com/fygWdRiQ

**Comment by Snownee** [comment]
It's currently incompatible with the Braincell mod.

**Comment by MC-Valdreth** [comment]
Thanks for the response. Do I need to report it on their page or are there already plans for compatibility in the future?

**Comment by Snownee** [comment]
Maybe not. It can be easily patched
