### ISSUE TITLE
RenderLayer binding crashes startup

### ISSUE THREAD

**Issue by ArtixAllMighty** [Snownee/Kiwi#40]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

6.1.1

### Modloader version

40.1.46

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

```
[00:04:07] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: Render layers can only be set during client loading! This might ideally be done from `FMLClientSetupEvent`.
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class snownee.kiwi.KiwiModules handleRegister(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.IllegalStateException: Render layers can only be set during client loading! This might ideally be done from `FMLClientSetupEvent`.

```

I'm trying to add compatibility with your mod and am using cursemaven to use your mod as a runtimeonly compile. 
when i try to launch my client, i get a crash and it basically tells that the kiwi mod is incorrectly registering their layers. 

edit: ive also got[ fruit trees ](https://www.curseforge.com/minecraft/mc-mods/fruit-trees/files/3756371)as a runtime only compile if that is of any interest.

**Comment by Snownee** [comment]
Could you provide a stacktrace? I can't reproduce the crash

**Comment by ArtixAllMighty** [comment]
https://www.toptal.com/developers/hastebin/sijisuxaqa.sql

It only happens when I launch the data gen from forge. i can start the client just fine. 

this is in my gradle build file 

```
dependencies{
    runtimeOnly fg.deobf("curse.maven:kiwi-303657:3817086")
    runtimeOnly fg.deobf("curse.maven:fruit-trees-355467:3756371")
}

repositories { //all of these are for adding crates compat
    mavenLocal()
   
    maven {
        name = 'Curse Maven'
        url = 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
}
```

**Comment by ArtixAllMighty** [comment]
it seems to be related to this 

https://github.com/Snownee/Kiwi/blob/9553714ef4a89dbaa83a36dccddbab27c4bf1de5/src/main/java/snownee/kiwi/KiwiModules.java#L42

where you call moduleinfo#handleRegister, in which you bind layers. 
the call is made in the block registry event, while the layers should best be set in the fmlclientsetupevent

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/kiwi/files/3827373

it is under review
