### ISSUE TITLE
Kiwi failed to load

### ISSUE THREAD

**Issue by Herobattler** [Snownee/Kiwi#46]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.3.4

### Modloader version

Forge:  43.2.8

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Kiwi failes to load when only clothconfig and kiwi are installed.

**Comment by Snownee** [comment]
Please provide your `latest.log` and crash report.

**Comment by Herobattler** [comment]
[latest.log](https://github.com/Snownee/Kiwi/files/11239284/latest.log)
[debug.log](https://github.com/Snownee/Kiwi/files/11239285/debug.log)
[crash-2023-04-15_13.44.43-fml.txt](https://github.com/Snownee/Kiwi/files/11239286/crash-2023-04-15_13.44.43-fml.txt)

**Comment by Snownee** [comment]
Did you edit the config file? You can try to delete the config file

**Comment by Herobattler** [comment]
I deleted it, it works now
