### ISSUE TITLE
Misupload?

### ISSUE THREAD

**Issue by dragoneyeeon** [Snownee/Kiwi#47]
### Mod loader

Forge

### Minecraft version

1.19.3

### Mod version

9.2.0

### Modloader version

Forge 44.1.23

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

The latest version that curseforge is showing available for Kiwi is now a file titled "PassableFoliage-1.19.3-forge-6.1.0.jar", which then causes an error message saying you need to download Kiwi.

**Comment by Snownee** [comment]
Thank you for informing me of this. CurseForge told me I have archived it
