### ISSUE TITLE
Tag tooltips broken in v11.5.1

### ISSUE THREAD

**Issue by mosharky** [Snownee/Kiwi#49]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.5.1

### Modloader version

Forge: 47.1.3

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://mclo.gs/aJQn1nt

### Issue description

Config is completely default. I'm assuming the `tagsTooltipAppendKeybindHint` config option means that you added a keybind, and the keybind is supposed to be Alt? Holding down left or right Alt isn't working either.

![image](https://github.com/Snownee/Kiwi/assets/32606683/ef4882c2-4063-4a0f-b618-d0189a3e8ede)

**Comment by Snownee** [comment]
Hi, you need to hold left Alt

**Comment by mosharky** [comment]
That didn't work for me as I said above

**Comment by Snownee** [comment]
no idea then... I can't reproduce it

**Comment by mosharky** [comment]
I just tested on Forge 47.2.20 and it seems to work on that. You should be able to reproduce it on the version of Forge 47.1.3, but I'd understand if you didn't want to make it work with an older forge version.

**Comment by Snownee** [comment]
I still cannot reproduce it in 47.1.3

**Comment by mosharky** [comment]
hmm im not sure then. I tested with exclusively Kiwi and Prism Launcher
