### ISSUE TITLE
Crash with Valkyrie Sky 

### ISSUE THREAD

**Issue by gundami** [Snownee/Kiwi#52]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.5.4

### Modloader version

Fabric loader 0.15.6, Fabric api 0.88.1

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/vMXMCm4V

### Issue description

Cannot work with Valkyrie Sky. I install fruitful fun and its dependency with VS2, then it crashed.

**Comment by Snownee** [comment]
This is a bug in VS2: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/617
