### ISSUE TITLE
Incompatible with search bar in Tom's Simple Storage

### ISSUE THREAD

**Issue by Etherrrr** [Snownee/Kiwi#56]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.5.4+

### Modloader version

Fabric: Loader 0.15.9 + API 0.92.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

items cannot be searched when the tags are folded
(REI works well)

![Snipaste_2024-04-07_22-57-44](https://github.com/Snownee/Kiwi/assets/20717049/dd05e788-b84e-48a9-8f6b-525496f290b3)
![Snipaste_2024-04-07_23-00-15](https://github.com/Snownee/Kiwi/assets/20717049/9c40b384-955c-4791-9a2d-e0e529f48d6c)

**Comment by Snownee** [comment]
the storage mod you are using only searches the tooltip content, not the actual tags. this should be a feature request to the storage mod and unrelated to my mod.
