### ISSUE TITLE
Crash on Startup with new version of Distant Horizons

### ISSUE THREAD

**Issue by NolanHewitt** [Snownee/Kiwi#58]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

2.0.3a

### Modloader version

Quilt 0.24

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/NolanHewitt/e8058a93c3ca1038e4048c1b5406eda4

### Issue description

[crash-2024-04-24_06.40.13-client.txt](https://github.com/Snownee/Kiwi/files/15093541/crash-2024-04-24_06.40.13-client.txt)

Crashes on startup after updating DH from 2.0.1 to 2.0.3

**Comment by SettingDust** [comment]
Better trim isn't working with Iris 1.7.0. Wrong repo.
