### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Elite911** [Snownee/Kiwi#59]
### Project

Kiwi

### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

[Forge 1.20.1] 11.8.11

### Modloader version

forge:47.3.1

### Modpack info

Better Minecraft 4

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

	Crash Report UUID: 32a61631-5bbb-429e-9a4a-6e0a36ab04ce
	FML: 47.3
	Forge: net.minecraftforge:47.3.1
	Kiwi Modules: 
		kiwi:block_components
		kiwi:block_templates
		kiwi:contributors
		kiwi:data
		kiwi:item_templates
		snowrealmagic:core
[15:08:52] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 13ee4f1d-40bd-4213-88fd-cb39a64a6e53

**Comment by SettingDust** [comment]
Provide crash report and log instead of lines copied by yourself.

**Comment by Elite911** [comment]
Crash Report: https://pastebin.com/3U0zph2p
Latest Log: https://pastebin.com/jzbW0MtX

Sorry, my bad. Thought it was for bugs. Maybe also write for crash reports what files you need when making a new issue.

**Comment by SettingDust** [comment]
No relation to Kiwi. It's `Ender's Delight` from crash report.
