### ISSUE TITLE
1.20.1 Mixin + Puzzleslib

### ISSUE THREAD

**Issue by Krimatoria** [Snownee/Kiwi#61]
### Project

Kiwi

### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.8.14

### Modloader version

47,3,5

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

UPD: apparently the problem is incompatibility with: Embeddiumplus

**Comment by Snownee** [comment]
No log file, and completely unrelated
