### ISSUE TITLE
[Suggestion] Tags in extended tooltips off by default

### ISSUE THREAD

**Issue by MarioSMB** [Snownee/Kiwi#64]
### Project

Kiwi

### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.3.6

### Modloader version

43.4.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Depending on the user's installed mods showing all tags in an item's description can lead to visual overload.  

As an example, an item from Tinker's Construct with several attached tags is shown to go off screen:  

![nbtissue](https://github.com/user-attachments/assets/0e96769b-e3a6-4579-9c73-3acff8218739)

This added tag tooltip info is hard to track down the source of and is generally not expected or desired by those who turn on detailed item descriptions to find which mod an item comes from, so I'd like to suggest that tags in tooltips be disabled by default.  
Thank you.

**Comment by Snownee** [comment]
hard to track down? that's not true. you can disable it in chat at the first time
