### ISSUE TITLE
Modpack crash in 1.20.1

### ISSUE THREAD

**Issue by Dodo19DBG** [Snownee/Kiwi#67]
### Project

Kiwi

### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

Latest (11.8.20)

### Modloader version

Forge 4.3.7

### Modpack info

https://drive.google.com/file/d/1iX9-tcOweC_N7KXXvUtLJwRmElK9U9xb/view?usp=drive_link

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/Dodo19DBG/874869e24c6de670370d748fcac2d1af

### Issue description

The game boot but suddenly crash when booting with kiwi, wich is needed for passable foliage. the game does not crash without kiwi and i can fully play survival without experiencing any bug. I sent you my modpack trough google drive.

**Comment by Snownee** [comment]
unrelated. you just installed oculus and iris at the same time
