### ISSUE TITLE
Issues locked to prevent feedback

### ISSUE THREAD

**Issue by MarioSMB** [Snownee/Kiwi#68]
### Project

Kiwi

### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

1.0.0

### Modloader version

43.2.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

An issue recently submitted was closed as not planned and immediately locked to prevent feedback.  
This can be seen as a toxic way to manage issues, so I wanted to suggest that you keep them unlocked in the future and instead decide whether to tune in to the discussions left behind, thank you.

P.S. I spent a good 20 minutes trying to figure out which mod was adding tags to item descriptions as a chat message is easy to miss in modded setups, you may want to reconsider that suggestion as a more sensible default - the screenshot did show an example of it causing visual issues afterall!

**Comment by Snownee** [comment]
Immersive Engineering also has this feature, and they don't even notify you. Have you reported this problem to them? Don't you think this is a bit unfair? And this is a debug feature that only works in advanced tooltips mode. Do you know what the "debug" means? Think about it.
