### ISSUE TITLE
contributor reward layer causes crashes when you click on invetory chest

### ISSUE THREAD

**Issue by SDUBZ** [Snownee/Kiwi#7]
* Forge Version: 1.15.1-30-36
 * Mod Version: Kiwi-1.15.1-2.6.0.jar

crasg report:
http://puu.sh/EYFFq/0df8a04568.txt

logs:
http://puu.sh/EYFFN/88fb6895df.log

**Comment by Snownee** [comment]
Thanks for telling me that!

https://www.curseforge.com/minecraft/mc-mods/kiwi/files/2858286
