### ISSUE TITLE
(alt) causing issues

### ISSUE THREAD

**Issue by ZealousVult2283** [Snownee/Kiwi#70]
### Project

Kiwi

### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

15.1.2

### Modloader version

0.16.9

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/ZealousVult2283/303d5de08c04416b8021fd21770af20d

### Issue description

So I am having game crashes now because of this "(alt)" text at the end of every item, which is causing problems with some mods and crashes my game. Is there a way to remove this or is it truly a bug?

**Comment by Snownee** [comment]
The latest log that you provided does not contain crash

**Comment by ZealousVult2283** [comment]
The (alt) is not directly causing the crash, but I want to know if the (alt) thing is a bug or not because it is causing a crash from another mod. as its conflicting with block tile entities it seems.

**Comment by Snownee** [comment]
If so, the crash should be contained there

**Comment by Snownee** [comment]
can you cause the crash again and send the log here?

**Comment by ZealousVult2283** [comment]
Here it is 
From what I know, this crash is caused when the enderman head from supplementaries breaks when shown because its block entity is broken because its name is techincally wrong from the (alt) at the end of the item tag.
[latest.log](https://github.com/user-attachments/files/17896620/latest.log)

**Comment by Snownee** [comment]
it's not related to Kiwi. please report to supplementaries.

**Comment by ZealousVult2283** [comment]
I did and they said the issue has something to do with the (alt) thing messing with their block entities, if it isnt a bug and the (alt) is intentional, is there a way I can remove it without needing to uninstall Kiwi?

**Comment by Snownee** [comment]
you can disable it in the config

**Comment by Snownee** [comment]
how did they say about it? I want to see the original replies

**Comment by ZealousVult2283** [comment]
How do you change the config? I know I need cloth but idk wheres the file, it doesnt show on mod menu, and I dont know the name of the config

**Comment by ZealousVult2283** [comment]
Also I recommend joining the supplementaries server to chat with their dev directly, he helps out a ton but he said; "there must be some mod that somehow is altering my own block tile entities valid blocks lists" and I went through my entire modpack, until there was only Kiwi left that could be causing this, and I approved of it by testing in a new modpack.

**Comment by Snownee** [comment]
I don't "alter blocks lists", I only modify item tooltips. just remove Kiwi and try it again in your old modpack

**Comment by ZealousVult2283** [comment]
Is there a way to remove the (alt) thing from Kiwi instead? Because I have on of your mods in my modpack and without Kiwi it wouldn't work I believe. You said its possible via config but I don't know where

**Comment by Snownee** [comment]
![image](https://github.com/user-attachments/assets/49c1b59a-2e0f-43bf-94f6-98bd7def9d4c)
![image](https://github.com/user-attachments/assets/61d962d9-38ee-4d9e-975d-27e96bf1ac66)
![image](https://github.com/user-attachments/assets/98beb1b6-f425-490a-8aee-b55ff8a14d54)

**Comment by ZealousVult2283** [comment]
wait why does my mod menu not show Kiwi?
