### ISSUE TITLE
1.15.1 null error

### ISSUE THREAD

**Issue by Yamza** [Snownee/Kiwi#8]
Crashes during loading

 * Forge Version: 30.0.41
 * Mod Version: Kiwi-1.15.1-2.6.2

Error: https://i.imgur.com/wS87xMI.png
Log:https://gist.github.com/Yamza/58dc1d25dbc7082143f1971dcc31d3a0

**Comment by Snownee** [comment]
Could you put [this](https://github.com/LXGaming/MixinBootstrap/releases/download/v1.0.0/MixinBootstrap-1.0.0.jar) in your mods folder?

**Comment by Yamza** [comment]
It did load with that in the folder.
